Controllers/BookController.cs
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Bookstore.Controllers{

    public class BookController : Controller{

        private readonly ApplicationDbContext _context;
         private readonly IWebHostEnvironment _webHostEnvironment;
        
        public BookController(ApplicationDbContext context, IWebHostEnvironment _webHost)
        {
            _context = context;
            _webHostEnvironment = _webHost;
        }

        [Authorize]
        public IActionResult Index(int page = 1 )
        {   
            if(page<1)page=1;
            var RealPage = page - 1;
            try{
                var Books = (_context.Books!=null) ? 
                                _context.Books.Include(b=>b.Category)
                                        .Include(b=>b.Borrowings)
                                                // .ToList()
                                                    .OrderBy(b=>b.Id)
                                                        .Skip((RealPage*10))
                                                            .Take(10)
                                                                .ToList() : new List<Book>();
                setPaginationConfig(page,10.0);

                return View(Books);
            }catch(Exception){
                return View();
            }
        }
        [Authorize]
        public IActionResult Create()
        {
            var categories = _context.Categories.ToList();
            ViewData["categories"] = categories;
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Book book)
        {
            
            
            try{
                if(ModelState.IsValid)
                {
                    if(book.CoverFile != null && book.CoverFile.Length > 0)
                    {
                        // Salvar o arquivo no servidor ou em um serviço de armazenamento (por exemplo, Azure Blob Storage)
                        // Aqui, você pode usar um método para salvar o arquivo e obter o caminho do arquivo.
                        string? name = await SaveFileAndGetPath(book.CoverFile);
                        if(name == null){
                            TempData["ErrorMessage"] = "Ficheiro não suportado.";
                            return RedirectToAction("Create");
                        }
                        book.Cover = name; 
                    }

                    _context.Books.Add(book);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Livro Adicionado";
                    return RedirectToAction("Index");
                }else{
                    TempData["ErrorMessage"] = "Não foi possível adicionar  o livro, tente novamente.";
                    return View();
                }
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Não foi possível adicionar  o livro, tente novamente.";
                return View();
                
            }
        }

        [Authorize]
        public IActionResult Details(int? id)
        {
            if(id == null)
            return NotFound();

            try{
                var Book = _context.Books.Include(b=>b.Borrowings).Include(b=>b.Category).ToList().Find(b=> b.Id == id);
                if(Book != null)
                {
                    return View(Book);
                }
                TempData["ErrorMessage"] = "Livro nao encontrado.";
                return RedirectToAction("Index");
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Não foi possível adicionar  o livro, tente novamente.";
                return View();
            }
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if(id == null)
            return NotFound();

            try{
                var Book = _context.Books.Include(b=>b.Borrowings).Include(b=>b.Category).ToList().Find(b=> b.Id == id);
                if(Book != null)
                {
                    var categories = _context.Categories.ToList();
                    ViewData["categories"] = categories;
                    return View(Book);
                }
                TempData["ErrorMessage"] = "Livro nao encontrado.";
                return RedirectToAction("Index");
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Ocorreu um erro, tente novamente.";
                return View();
            }
        }


         [HttpPost]
         [Authorize]
        public async Task<IActionResult> Edit(int id,Book book)
        {
            
            
            try{
                if(ModelState.IsValid)
                {
                    if(book.CoverFile != null && book.CoverFile.Length > 0)
                    {
                        // Salvar o arquivo no servidor ou em um serviço de armazenamento (por exemplo, Azure Blob Storage)
                        // Aqui, você pode usar um método para salvar o arquivo e obter o caminho do arquivo.
                        string? name = await SaveFileAndGetPath(book.CoverFile);
                        if(name == null){
                            TempData["ErrorMessage"] = "Ficheiro não suportado.";
                            return RedirectToAction("Edit",id);
                        }
                        book.Cover = name; 
                    }

                    _context.Books.Update(book);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Livro Actualizado";
                    return RedirectToAction("Edit",id);
                }else{
                    TempData["ErrorMessage"] = "Não foi possível actualizar  o livro, tente novamente.";
                    return View();
                }
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Não foi possível actualizar  o livro, tente novamente.";
                return View();
                
            }
        }


        [HttpPost]
        [Authorize]
        public IActionResult Delete(int? id)
        {

            try{
                if(id == null)return NotFound();
                var Book = _context.Books.Find(id);

                if (Book == null) return NotFound();
                _context.Books.Remove(Book);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Livro Removido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }

        // HELPERS

        private async Task<string?> SaveFileAndGetPath(IFormFile file)
        {
            string [] AllowedTypes = new string[]{"image/jpeg","image/gif","image/jpg","image/png"};
                // Implemente a lógica para salvar o arquivo no servidor ou em um serviço de armazenamento
                // Retorne o caminho do arquivo após o salvamento

                // Exemplo básico: Salvar o arquivo no diretório wwwroot/uploads
                if(!AllowedTypes.Contains(file.ContentType)){
                    
                    return null;
                }
                Console.WriteLine("CONTENT TYPE: "+file.ContentType);
                var uploadsDirectory = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");
                if (!Directory.Exists(uploadsDirectory))
                Directory.CreateDirectory(uploadsDirectory);

                var fileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(file.FileName);
                var filePath = Path.Combine(uploadsDirectory, fileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }

                // Retorna o caminho do arquivo salvo
                return "/uploads/" + fileName;
        }

        private void setPaginationConfig(int page, double size)
        {
                double pages = _context.Books.Count() / size;
                ViewData["total_pages"] = Math.Ceiling(pages);
                Console.WriteLine("TOTAL PAGES = " +ViewData["total_pages"] );
                ViewData["actual_page"] = page;
                ViewData["next_page"] = page + 1;
                ViewData["prev_page"] = page==1?page:page - 1;
        }
    }
}

Controllers/ClientController.cs
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Bookstore.Controllers{

    public class ClientController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ClientController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index(int page = 1)
        {
            try{
                if(page<1)page=1;
                var RealPage = page - 1;
                var Clients = (_context.Clients!=null)?
                                        _context.Clients
                                            .OrderBy(c=>c.Id)
                                                .Skip((RealPage*5))
                                                    .Take(5).ToList()
                                                        :new List<Client>();
                setPaginationConfig(page,5.0);
                return View(Clients);
            }catch(Exception)
            {
                return RedirectToAction("Create");
            }
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Client client)
        {
            try{
                if(ModelState.IsValid)
                {
                    _context.Clients.Add(client);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Cliente Adicionado";
                    return RedirectToAction("Index");
                }else
                {
                    return View();
                }
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Falha ao adicionar Cliente";
                return View();
            }
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            var Client = _context.Clients.Find(id);
            if(Client == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            return View(Client);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int? id, Client client)
        {
            try{
                if(client.Id != id)return NotFound();
                if(ModelState.IsValid)
                {
                    _context.Clients.Update(client);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Cliente Alterado";
                    return RedirectToAction("Index");
                }else
                {
                    return View();
                }
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Falha ao actualizar dados do Cliente";
                return View();
            }
        }

        [Authorize]
        public IActionResult Borrowings(int? id)
        {
            try{
                if(id == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            var Client = _context.Clients.Include(c=>c.Borrowings).ThenInclude(b=>b.Book).ToList().Find(c=>c.Id == id);
            if(Client == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            return View(Client);
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Falha ao buscar dados do Cliente";
                return View();
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int? id)
        {

            try{
                if(id == null)return NotFound();
                var Client = _context.Clients.Find(id);

                if (Client == null) return NotFound();
                _context.Clients.Remove(Client);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Ciente Removido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }
         private void setPaginationConfig(int page, double size)
        {
                double pages = _context.Clients.Count() / size;
                ViewData["total_pages"] = Math.Ceiling(pages);
                Console.WriteLine("TOTAL PAGES = " +ViewData["total_pages"] );
                ViewData["actual_page"] = page;
                ViewData["next_page"] = page + 1;
                ViewData["prev_page"] = page==1?page:page - 1;
        }
    }
}

Controllers/UserController.cs
using Bookstore.Data;
using Bookstore.Models;
using Bookstore.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bookstore.Controllers{
    
    public class UserController : Controller{

        private readonly UserManager<AppUser> _userManager;
        private readonly ApplicationDbContext _db;
       

        public UserController(UserManager<AppUser> userManager,ApplicationDbContext applicationDbContext)
        {
            _db = applicationDbContext;
            _userManager = userManager;
        }

        
        public  IActionResult Index()
        {
            try{
                var users = _db.AppUsers.ToList();
                return View(users);
            }catch(Exception e)
            {
                Console.WriteLine("ERROR"+e.Message);
                Console.WriteLine("ERROR"+e.InnerException.Message);
                return  NotFound();
            }
        }
        public IActionResult Create()
        {
            return  View();
        }

         [HttpPost]
        public async Task<IActionResult> Create(CreateViewModel createViewModel)
        {
            try{
                if(ModelState.IsValid)
                {
                    var user = new AppUser{Email = createViewModel.Email, UserName = createViewModel.UserName};
                    var result = await _userManager.CreateAsync(user,"#aB123");
                    if(result.Succeeded)
                    {
                        TempData["SuccessMessage"] = "Utilizador Adicionado";
                        return RedirectToAction("Index");
                    }
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("Email",error.Description);    
                    }
                }
                return View(createViewModel);

            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var userIsAuthenticated = User.Identity.IsAuthenticated;
    @* string userEmail = User.FindFirst("name"); *@
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom_admin.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookstore.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/6b4ddefc79.js" crossorigin="anonymous"></script>
    
</head>
<body>
    @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@

    <!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav  sidebar sidebar-dark accordion" style="background-color: #222;"  id="accordionSidebar">
        <a class="sidebar-brand d-flex align-items-center justify-content-center" 
        href="#">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="far fa-book"></i>
            </div>
            <div class="sidebar-brand-text mx-3">BOOKSTORE</div>
        </a>
        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" asp-controller="Home" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" asp-controller="Book" asp-action="Index">
                <i class="fas fa-fw fa-book"></i>
                <span>Livros</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" asp-controller="Client" asp-action="Index">
                <i class="fas fa-users"></i>
                <span>Clientes</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse2"
            aria-expanded="true" aria-controls="collapseTwo">
                <i class="fas fa-book"></i>
                <span>Empréstimos</span>
            </a>
            <div id="collapse2" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                <div class="bg-white py-2 collapse-inner rounded">
                    <a class="collapse-item" asp-controller="Borrowing" asp-action="Index">Lista de Empréstimos</a>
                    <a class="collapse-item" asp-controller="Penalty" asp-action="Index">Multas Aplicadas</a>
                </div>
            </div>

        </li>
        <li class="nav-item active">
            <a class="nav-link" asp-controller="Category" asp-action="Index">
                <i class="fas fa-users"></i>
                <span>Categorias</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" asp-controller="User" asp-action="Index">
                <i class="fas fa-lock"></i>
                <span>Utilizadores</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="#" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"
                            data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt "></i>
                                <span>Terminar Sessão</span>
                            </a>
                            <form id="logout-form" method="POST" class="d-none"
                            asp-controller="Account" asp-action="LogOut">
                                        
                            </form>
        </li>
    </ul>
    
    <!-- End of Sidebar -->

    
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                
                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
                     <!-- Nav Item - User Information -->
                     <li class="nav-item dropdown no-arrow">
                        @if(SignInManager.IsSignedIn(User)){
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           
                            <span class="mr-2 d-none d-md-inline text-gray-600 ">@UserManager.GetUserName(User)</span>
                            <!-- <img class="img-profile rounded-circle"
                                src="img/undraw_profile.svg"> -->
                            
                                <i class="fas fa-user"></i>
                            
                        </a>
                        }
                        @if (userIsAuthenticated)
                        {
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           
                            <span class="mr-2 d-none d-md-inline text-gray-600 ">@User.Identity.Name </span>
                            <!-- <img class="img-profile rounded-circle"
                                src="img/undraw_profile.svg"> -->
                            
                                <i class="fas fa-user"></i>
                            
                            </a>
                        }
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                            aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Perfil
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400"></i>
                                Definições
                            </a>
                            @* <a class="dropdown-item" href="#">
                                <i class="fas fa-globe fa-sm fa-fw mr-2 text-gray-400"></i>
                                Ir ao Portal
                            </a> *@
                            @if(userIsAuthenticated){
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"
                            data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Terminar Sessão
                            </a>
                            @* <form id="logout-form" action="#" method="POST" class="d-none">
                                        
                            </form> *@
                            }
                            
                        </div>
                    </li>
                </ul>
                <!-- End of TopBar Navbar -->
            
            </nav>
            <!-- End of TopBar -->


             <!-- Begin Page Content -->
            <div class="container-fluid">
                
                <!-- O CONTEUDO DA PAGINA -->
                

                @RenderBody()


            </div>
             <!-- End of Page COntent -->
            <!-- FIM DO CONTEUDO DA PAGINA -->
        </div>
        <!-- End of Main Content -->

    </div>
     <!-- End of Content Wrapper -->


</div>
@* End of Page Wrapper *@

<!-- MODAL PARA STATUS DE OPERALÇÃO -->
@if(TempData["ErrorMessage"]!=null){
<!-- Modal -->
<div class="modal fade" id="modalError" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger font-weight-bolder " id="exampleModalLabel"style="font-size: 1.5em;" >Ocorreu um erro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-dark text-center" style="font-size: 1.2em;">
            @TempData["ErrorMessage"]
      </div>
    </div>
  </div>
</div>
                       
}

@if(TempData["SuccessMessage"]!=null){
<div class="modal fade" id="modalSuccess" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-success font-weight-bolder " style="font-size: 1.5em;"id="exampleModalLabel" >Concluído</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-dark text-canter" style="font-size: 1.2em;">
            @TempData["SuccessMessage"]
      </div>
    </div>
  </div>
</div>
                       
}
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.easing.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/custom.js" asp-append-version="true"></script>
    <script src="~/js/custom_admin.js" asp-append-version="true"></script>
    @* <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script> *@
    <script>
        var modal = document.getElementById('modalError');
        if(modal==null)
        {
            console.log(modal);
        }else{
                
                 let modalError =new bootstrap.Modal(document.getElementById('modalError'),{

                });
                if(modalError!=null)
                {
                    modalError.show();
                }
        }
        
        var modal1 = document.getElementById('modalSuccess')
        if(modal1==null)
        {
            console.log(modal1);
        }else{
            let modalSuccess =new bootstrap.Modal(document.getElementById('modalSuccess'),{

            });
            if(modalSuccess!=null)
            {
                modalSuccess.show();
            }
        }


       

        
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>