Models/Borrowing.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Bookstore.Models
{
    public class Borrowing
    {
        
        public int Id{get;set;}
        
        public DateTime RequestDate{get;set;} = DateTime.Now;
        public DateTime ReturnDate{get;set;}
        public bool Returned{get;set;} = false;
        public bool PrizeViolated{get;set;} = false;
        public int BookId{get;set;}
        public Book? Book{get;set;}
        public int ClientId{get;set;} 
        public Client? Client{get;set;}
        public Penalty? Penalty{get;set;} 
        
    }    
}

Models/Client.cs
using System.ComponentModel.DataAnnotations;

namespace Bookstore.Models
{
    public class Client
    {
        public int Id{get;set;}
        [Required(ErrorMessage="O nome do 'Cliente' é obrigatório")]
        public string Name{get;set;} = null!;
        [Required(ErrorMessage="O email do 'Cliente' é obrigatório")]
        public string Email{get;set;} = null!;
        [Required(ErrorMessage="Uma Data de nascimento é obrigatória")]
        public DateTime BornDate{get;set;} 
        public bool Active{get;set;} = true;
        public List<Borrowing> Borrowings {get;set;} = new List<Borrowing>();
    }    
}

ViewModels/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bookstore.ViewModels{

    public class CreateViewModel{


        [Required]
        [EmailAddress]
        public string Email{get;set;}

        [Required]
        public string UserName{get;set;}

        

    }
}

Controllers/BorrowingController.cs
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Bookstore.Controllers{

    public class BorrowingController : Controller{

        public readonly ApplicationDbContext _context;
        public BorrowingController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index(int page = 1)
        {
            try{
                if(page<1)page=1;
                var RealPage = page - 1;

                var Borrowings = (_context.Borrowings != null)?_context.Borrowings
                                                .Include(b=>b.Book)
                                                    .Include(b=>b.Client)
                                                        .OrderBy(b=>b.Id)
                                                            .Skip((RealPage*5))
                                                                .Take(5)
                                                                 .ToList():new List<Borrowing>();
                setPaginationConfig(page,5.0);
                return View(Borrowings);
            }catch(Exception)
            {
                return View();
            }
        }

        [Authorize]
        public IActionResult SelectBook()
        {
            try{
                var Books = (_context.Books!=null)?_context.Books.Include(b=>b.Category).Include(b=>b.Borrowings).ToList():new List<Book>();
                return View(Books);
            }catch(Exception){
                return View();
            }
        }

        [Authorize]
        public IActionResult BorrowBook(int? id)
        {
            try{
                if(id == null)return NotFound();

                var Book = _context.Books.Find(id);
                if(Book == null) return NotFound();

                var Clients = (_context.Clients!=null)?_context.Clients.ToList():new List<Client>();
                ViewData["Book"] = Book;
                return View("SelectClient",Clients);
            }catch(Exception)
            {
                return NotFound();
            }
        }

        [Authorize]
        public IActionResult Create(int id, int book)
        {
            try{
                if(id == null || book == null)return NotFound();
                var Book = _context.Books.Find(book);
                if(Book == null) return NotFound();

                var Client = _context.Clients.Find(id);

                if(Client == null) return NotFound();
                ViewData["Book"] = Book;
                ViewData["Client"] = Client;
                return View();
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create([Bind("RequestDate","ReturnDate","Returned","PrizeViolated","BookId","ClientId")]Borrowing Borrowing)
        {
            try{
                Console.WriteLine("ID:"+Borrowing.Id);
                Console.WriteLine("Cli_Id:"+Borrowing.ClientId);
                Console.WriteLine("Book_Id:"+Borrowing.BookId);
                Console.WriteLine("Return:"+Borrowing.ReturnDate);
                    _context.Entry(Borrowing).Property("Id").IsModified = false;
                    _context.Borrowings.Add(Borrowing);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Emprestimo Concluido";
                    return RedirectToAction("Index");
                
                
            }catch(Exception ex)
            {
                TempData["ErrorMessage"] = @"Ocorreu um problema tente outra vez {ex.Message}";
                return RedirectToAction("Index");
            }
        }


        [Authorize]
        public IActionResult Show(int? id)
        {
            try{
                if(id == null)
                {
                    return NotFound();
                }

                var Borrowing = _context.Borrowings.Include(b=>b.Client)
                                                        .Include(b=>b.Book)
                                                            .Include(b=>b.Penalty)
                                                                .ToList().Find(b=>b.Id == id);
                if(Borrowing == null){
                    TempData["ErrorMessage"] = "Emprestimo não encontrado";
                    return RedirectToAction("Index");
                }
                return View(Borrowing);
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        [Authorize]
        public IActionResult Devolver(int? id,Borrowing updateBorrowing)
        {

            try{
                if(id == null)return NotFound();
                var borrowing = _context.Borrowings.Find(updateBorrowing.Id);

                if (borrowing == null) return NotFound();
                borrowing.Returned = true;
                if(borrowing.ReturnDate < DateTime.Now){
                    borrowing.PrizeViolated = true;
                }
                _context.Borrowings.Update(borrowing);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Livro Devolvido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int? id)
        {

            try{
                if(id == null)return NotFound();
                var borrowing = _context.Borrowings.Find(id);

                if (borrowing == null) return NotFound();
                _context.Borrowings.Remove(borrowing);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Empréstimo Removido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }


        private void setPaginationConfig(int page, double size)
        {
                double pages = _context.Borrowings.Count() / size;
                ViewData["total_pages"] = Math.Ceiling(pages);
                Console.WriteLine("TOTAL PAGES = " +ViewData["total_pages"] );
                ViewData["actual_page"] = page;
                ViewData["next_page"] = page + 1;
                ViewData["prev_page"] = page==1?page:page - 1;
                
        }

    }
}

Controllers/ClientController.cs
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Bookstore.Controllers{

    public class ClientController : Controller
    {

        private readonly ApplicationDbContext _context;

        public ClientController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index(int page = 1)
        {
            try{
                if(page<1)page=1;
                var RealPage = page - 1;
                var Clients = (_context.Clients!=null)?
                                        _context.Clients
                                            .OrderBy(c=>c.Id)
                                                .Skip((RealPage*5))
                                                    .Take(5).ToList()
                                                        :new List<Client>();
                setPaginationConfig(page,5.0);
                return View(Clients);
            }catch(Exception)
            {
                return RedirectToAction("Create");
            }
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Client client)
        {
            try{
                if(ModelState.IsValid)
                {
                    _context.Clients.Add(client);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Cliente Adicionado";
                    return RedirectToAction("Index");
                }else
                {
                    return View();
                }
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Falha ao adicionar Cliente";
                return View();
            }
        }

        [Authorize]
        public IActionResult Edit(int? id)
        {
            if(id == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            var Client = _context.Clients.Find(id);
            if(Client == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            return View(Client);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int? id, Client client)
        {
            try{
                if(client.Id != id)return NotFound();
                if(ModelState.IsValid)
                {
                    _context.Clients.Update(client);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Cliente Alterado";
                    return RedirectToAction("Index");
                }else
                {
                    return View();
                }
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Falha ao actualizar dados do Cliente";
                return View();
            }
        }

        [Authorize]
        public IActionResult Borrowings(int? id)
        {
            try{
                if(id == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            var Client = _context.Clients.Include(c=>c.Borrowings).ThenInclude(b=>b.Book).ToList().Find(c=>c.Id == id);
            if(Client == null)
            {
                TempData["ErrorMessage"] = "Cliente não encontrado";
                return RedirectToAction("Index");
            }
            return View(Client);
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Falha ao buscar dados do Cliente";
                return View();
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int? id)
        {

            try{
                if(id == null)return NotFound();
                var Client = _context.Clients.Find(id);

                if (Client == null) return NotFound();
                _context.Clients.Remove(Client);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Ciente Removido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }
         private void setPaginationConfig(int page, double size)
        {
                double pages = _context.Clients.Count() / size;
                ViewData["total_pages"] = Math.Ceiling(pages);
                Console.WriteLine("TOTAL PAGES = " +ViewData["total_pages"] );
                ViewData["actual_page"] = page;
                ViewData["next_page"] = page + 1;
                ViewData["prev_page"] = page==1?page:page - 1;
        }
    }
}

Views/Client/Borrowings.cshtml
@model Bookstore.Models.Client
@{
    ViewData["Title"] =Model.Name +" - Empréstimos";
}

<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h3 class="my-6 text-2xl font-semibold text-gray-700 ">
            Empréstimos de @Model.Name
        </h3>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs">
            
            @* <div class="p-2 d-flex justify-content-between align-items">
              <div>
                <a class="btn btn-primary" asp-action="SelectBook">Novo Empréstimo</a>
              </div>
              
            </div> *@


            <div class="border rounded">
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Livro</th>
                    <th scope="col">Data de Empréstimo</th>
                    <th scope="col">Data de Devolução</th>
                    <th scope="col">Estado </th>
                    <th scope="col">Prazo Violado? </th>
                    <th scope="col">Acções</th>
                  </tr>
                </thead>
                <tbody>
                    @if(Model.Borrowings != null){
                  @foreach(var item in Model.Borrowings){
                    
                    <tr style="color: black;">
                        <td>@item.Id</td>
                        <td> @item.Book.Title</td>
                        @* <td> @item.Isbn</td> *@
                        <td> @item.RequestDate</td>
                        <td> @item.ReturnDate</td>
                        <td>
                        @if(item.Returned==true)
                        {
                            <span class="text-primary">Devolvido</span>    
                        }else{
                            <span class="text-info">Requisitado</span>
                        }
                        </td>
                        <td>
                        @if(item.PrizeViolated==true)
                        {
                            <span class="text-danger ">Violado</span>    
                        }else if((item.ReturnDate < DateTime.Now) && item.Returned == false){
                            <span class="text-danger ">Violado</span>
                        }
                        else{
                            <span class="text-secondary ">Não</span>
                        }
                        </td>
                        <td class="d-flex">
                            @if(item.Returned != true)
                            {
                                <a  class=" btn  btn-success btn-sm mr-3"
                                asp-controller="Borrowing" asp-action="Show" asp-route-id="@item.Id">
                                    Devolver
                                </a>
                            }else{
                              <a  class=" btn  btn-info btn-sm mr-3"
                                asp-controller="Borrowing" asp-action="Show" asp-route-id="@item.Id">
                                    Detalhes
                                </a>
                            }   
                            
                        </td>
                    
                        
                    </tr>
                    }
                    }else{
                        <tr>
                            <td colspan="3" class="text-center">Sem Resultados</td>
                        </tr>
                    }
                </tbody>
              </table>
            </div>
            <div class="mt-2 p-2 w-full d-flex justify-content-center">
              <div class="">
              
              </div>
            </div>

        </div>


    </div>
</main>

Views/Client/Create.cshtml
@model Bookstore.Models.Client
@{
    ViewData["Title"] ="Adicionar Cliente";
}
<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 ">
            Adicionar Cliente
        </h2>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs">
            
        <form class="form" asp-action="Create" method="post" >
                    <div class="form-row">
                        <div class="form-group col-12 col-md-3 mr-5">
                            <label for="">Nome</label>
                            <input type="text" asp-for="Name" class="form-control" placeholder="Nome do Cliente">
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>
                        <div class="form-group col-12 col-md-3 mr-5">
                            <label for="">Email</label>
                            <input type="email" asp-for="Email" class="form-control" placeholder="Email do Cliente">
                            <span class="text-danger" asp-validation-for="Email"></span>
                        </div>
                        <div class="form-group col-12 col-md-3 mr-5">
                            <label for="">Data de Nascimento</label>
                            <input type="date" asp-for="BornDate" class="form-control" >
                            <span class="text-danger" asp-validation-for="BornDate"></span>
                        </div>
                                
                    </div>
                    <div class=" form-row mt-3">
                        <div class="form-group col-12 col-md-5">
                            <input type="submit" value="Adicionar" class="w-50 btn btn-md btn-primary">
                    
                        </div>
                    </div>
                </form>
           

        </div>


    </div>
</main>

Views/Client/Edit.cshtml
@model Bookstore.Models.Client
@{
    ViewData["Title"] ="Actualizar Cliente";
}
<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 ">
            Actualizar Cliente
        </h2>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs">
            
        <form class="form" asp-action="Edit" method="post" >
                    <input type="hidden" name="Id" asp-for="Id">
                    <div class="form-row">
                        <div class="form-group col-12 col-md-3 mr-5">
                            <label asp-for="Name">Nome</label>
                            <input type="text" asp-for="Name" class="form-control" placeholder="Nome do Cliente">
                            <span class="text-danger" asp-validation-for="Name"></span>
                        </div>
                        <div class="form-group col-12 col-md-3 mr-5">
                            <label for="">Email</label>
                            <input type="email" asp-for="Email" class="form-control" placeholder="Email do Cliente">
                            <span class="text-danger" asp-validation-for="Email"></span>
                        </div>
                        <div class="form-group col-12 col-md-3 mr-5">
                            <label for="">Data de Nascimento</label>
                            <input type="date" asp-for="BornDate" class="form-control" >
                            <span class="text-danger" asp-validation-for="BornDate"></span>
                        </div>
                         <div class="form-group col-12 col-md-3 mr-5">
                            <label for="">Estado</label>
                            <select class="form-select" asp-for="Active">
                                <option value="true">Activo</option>
                                <option value="false">Suspenso</option>
                            </select>
                            <span class="text-danger" asp-validation-for="Active"></span>
                        </div>
                                
                    </div>
                    <div class=" form-row mt-3">
                        <div class="form-group col-12 col-md-5">
                            <input type="submit" value="Guardar" class="w-50 btn btn-md btn-primary">
                    
                        </div>
                    </div>
                </form>
           

        </div>


    </div>
</main>

Views/Client/Index.cshtml
@model IEnumerable<Bookstore.Models.Client>
@{
    ViewData["Title"] ="Lista de Clientes";
    var nextPage = ViewData["next_page"];
    var prevPage = ViewData["prev_page"];
    var actualPage = ViewData["actual_page"];
    var totalPages = int.Parse(ViewData["total_pages"].ToString());
}

<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 ">
            Lista de Clientes
        </h2>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs">
            
            <div class="p-2 d-flex justify-content-between align-items">
              <div>
                <a class="btn btn-primary" asp-action="Create">Adicionar Cliente</a>
              </div>
              
            </div>


            <div class="border rounded">
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Email</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col">Estado</th>
                    <th scope="col">Acções</th>
                  </tr>
                </thead>
                <tbody>
                    @if(Model != null){
                  @foreach(var item in Model){
                    <tr style="color: black;">
                        <td>@item.Id</td>
                        <td> @item.Name</td>
                        <td> @item.Email</td>
                        <td> @item.BornDate</td>
                        <td class="text-center">
                            @if(item.Active == true){
                                <span class="btn btn-sm btn-success">Activo</span>
                            }
                            else{
                                <span class="btn btn-sm btn-danger">Suspenso</span>
                            }
                        </td>
                        <td class="d-flex">
                          
                          
                          <a  class=" btn  btn-primary btn-sm mr-3"
                          asp-action="Edit" asp-route-id="@item.Id">
                            Editar
                          </a>
                          <a asp-controller="Client" asp-action="Borrowings" asp-route-id="@item.Id" class=" btn  btn-info btn-sm mr-3">
                            Empréstimos
                          </a>
                          @* <a  class=" btn  btn-danger btn-sm mr-3">
                            Eliminar
                            </a> *@

                        </td>
                        
                    </tr>
                    }
                    }else{
                        <tr>
                            <td colspan="3" class="text-center">Sem Resultados</td>
                        </tr>
                    }
                </tbody>
              </table>
            </div>
            <div class="mt-2 p-2 w-full d-flex justify-content-center">
              <div class="">
                       <nav aria-label="Page navigation example">
                        <ul class="pagination">
                          @if((int)prevPage==(int)actualPage)
                          {
                            <li class="page-item disabled"><a class="page-link " asp-action="Index" asp-route-page="@prevPage">Anterior</a></li>
                          }else{
                            <li class="page-item"><a class="page-link  " asp-action="Index" asp-route-page="@prevPage">Anterior</a></li>
                          }
                          @for(int i = 1;i <= totalPages; i++)
                          {
                            @if(actualPage.ToString() == i.ToString())
                            {
                              <li class="page-item bg-primary  text-light active"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li> 
                            }
                            else{
                              <li class="page-item  text-light"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li> 
                            }
                          }
                          @if((int)nextPage>totalPages)
                          {
                            <li class="page-item disabled"><a class="page-link  " asp-action="Index" asp-route-page="@nextPage">Próximo</a></li>
                          }else{
                            <li class="page-item"><a class="page-link  " asp-action="Index" asp-route-page="@nextPage">Próximo</a></li>
                          }
                          
                        </ul>
                      </nav> 
              </div>
            </div>

        </div>


    </div>
</main>