Models/Borrowing.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace Bookstore.Models
{
    public class Borrowing
    {
        
        public int Id{get;set;}
        
        public DateTime RequestDate{get;set;} = DateTime.Now;
        public DateTime ReturnDate{get;set;}
        public bool Returned{get;set;} = false;
        public bool PrizeViolated{get;set;} = false;
        public int BookId{get;set;}
        public Book? Book{get;set;}
        public int ClientId{get;set;} 
        public Client? Client{get;set;}
        public Penalty? Penalty{get;set;} 
        
    }    
}

ViewModels/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bookstore.ViewModels{

    public class CreateViewModel{


        [Required]
        [EmailAddress]
        public string Email{get;set;}

        [Required]
        public string UserName{get;set;}

        

    }
}

Controllers/BorrowingController.cs
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Bookstore.Controllers{

    public class BorrowingController : Controller{

        public readonly ApplicationDbContext _context;
        public BorrowingController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index(int page = 1)
        {
            try{
                if(page<1)page=1;
                var RealPage = page - 1;

                var Borrowings = (_context.Borrowings != null)?_context.Borrowings
                                                .Include(b=>b.Book)
                                                    .Include(b=>b.Client)
                                                        .OrderBy(b=>b.Id)
                                                            .Skip((RealPage*5))
                                                                .Take(5)
                                                                 .ToList():new List<Borrowing>();
                setPaginationConfig(page,5.0);
                return View(Borrowings);
            }catch(Exception)
            {
                return View();
            }
        }

        [Authorize]
        public IActionResult SelectBook()
        {
            try{
                var Books = (_context.Books!=null)?_context.Books.Include(b=>b.Category).Include(b=>b.Borrowings).ToList():new List<Book>();
                return View(Books);
            }catch(Exception){
                return View();
            }
        }

        [Authorize]
        public IActionResult BorrowBook(int? id)
        {
            try{
                if(id == null)return NotFound();

                var Book = _context.Books.Find(id);
                if(Book == null) return NotFound();

                var Clients = (_context.Clients!=null)?_context.Clients.ToList():new List<Client>();
                ViewData["Book"] = Book;
                return View("SelectClient",Clients);
            }catch(Exception)
            {
                return NotFound();
            }
        }

        [Authorize]
        public IActionResult Create(int id, int book)
        {
            try{
                if(id == null || book == null)return NotFound();
                var Book = _context.Books.Find(book);
                if(Book == null) return NotFound();

                var Client = _context.Clients.Find(id);

                if(Client == null) return NotFound();
                ViewData["Book"] = Book;
                ViewData["Client"] = Client;
                return View();
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create([Bind("RequestDate","ReturnDate","Returned","PrizeViolated","BookId","ClientId")]Borrowing Borrowing)
        {
            try{
                Console.WriteLine("ID:"+Borrowing.Id);
                Console.WriteLine("Cli_Id:"+Borrowing.ClientId);
                Console.WriteLine("Book_Id:"+Borrowing.BookId);
                Console.WriteLine("Return:"+Borrowing.ReturnDate);
                    _context.Entry(Borrowing).Property("Id").IsModified = false;
                    _context.Borrowings.Add(Borrowing);
                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Emprestimo Concluido";
                    return RedirectToAction("Index");
                
                
            }catch(Exception ex)
            {
                TempData["ErrorMessage"] = @"Ocorreu um problema tente outra vez {ex.Message}";
                return RedirectToAction("Index");
            }
        }


        [Authorize]
        public IActionResult Show(int? id)
        {
            try{
                if(id == null)
                {
                    return NotFound();
                }

                var Borrowing = _context.Borrowings.Include(b=>b.Client)
                                                        .Include(b=>b.Book)
                                                            .Include(b=>b.Penalty)
                                                                .ToList().Find(b=>b.Id == id);
                if(Borrowing == null){
                    TempData["ErrorMessage"] = "Emprestimo não encontrado";
                    return RedirectToAction("Index");
                }
                return View(Borrowing);
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }


        [HttpPost]
        [Authorize]
        public IActionResult Devolver(int? id,Borrowing updateBorrowing)
        {

            try{
                if(id == null)return NotFound();
                var borrowing = _context.Borrowings.Find(updateBorrowing.Id);

                if (borrowing == null) return NotFound();
                borrowing.Returned = true;
                if(borrowing.ReturnDate < DateTime.Now){
                    borrowing.PrizeViolated = true;
                }
                _context.Borrowings.Update(borrowing);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Livro Devolvido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int? id)
        {

            try{
                if(id == null)return NotFound();
                var borrowing = _context.Borrowings.Find(id);

                if (borrowing == null) return NotFound();
                _context.Borrowings.Remove(borrowing);
                _context.SaveChanges();
                TempData["SuccessMessage"] = "Empréstimo Removido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }


        private void setPaginationConfig(int page, double size)
        {
                double pages = _context.Borrowings.Count() / size;
                ViewData["total_pages"] = Math.Ceiling(pages);
                Console.WriteLine("TOTAL PAGES = " +ViewData["total_pages"] );
                ViewData["actual_page"] = page;
                ViewData["next_page"] = page + 1;
                ViewData["prev_page"] = page==1?page:page - 1;
                
        }

    }
}

Controllers/PenaltyController.cs
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Bookstore.Controllers{

    public class PenaltyController : Controller{

        public readonly ApplicationDbContext _context;
        public PenaltyController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize]
        public IActionResult Index(int page = 1)
        {
            try{
                if(page<1)page=1;
                var RealPage = page - 1;

                var Penalties = (_context.Penalties != null)?_context.Penalties
                                                .Include(b=>b.Borrowing)
                                                .ThenInclude(b=>b.Book)
                                                .Include(b=>b.Borrowing)
                                                .ThenInclude(b=>b.Client)
                                                        .OrderBy(c=>c.Id)
                                                        .Skip((RealPage*5))
                                                            .Take(5).ToList():new List<Penalty>();
                setPaginationConfig(page,5.0);

                return View(Penalties);
            }catch(Exception)
            {
                return View();
            }
        }


        [Authorize]
        public IActionResult Create(int? id)
        {
            try{
                if(id == null)return NotFound();
                var Borrowing = _context.Borrowings.Include(b=>b.Client)
                                                        .Include(b=>b.Book)
                                                            .Include(b=>b.Penalty)
                                                                .ToList().Find(b=>b.Id == id);
                ViewData["Borrowing"] = Borrowing;
                return View();
            }catch(Exception)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create([Bind("DateAplied","Solved","Value","BorrowingId")]Penalty Penalty)
        {
            try{
                    // _context.Entry(Borrowing).Property("Id").IsModified = false;
                    _context.Penalties.Add(Penalty);
                    
                    // suspend Client
                    int BorrowingId = Penalty.BorrowingId;
                    var Borrowing = _context.Borrowings.Find(BorrowingId);
                    if(Borrowing !=null)
                    {
                        var Client = _context.Clients.Find(Borrowing.ClientId);
                        if(Client!=null)
                        {
                            Client.Active = false;
                            _context.Clients.Update(Client);
                        }
                    }

                    _context.SaveChanges();
                    TempData["SuccessMessage"] = "Multa Aplicada";
                    return RedirectToAction("Index");
                
                
            }catch(Exception ex)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }


        [Authorize]
        public IActionResult Show(int? id)
        {
            try{
                if(id == null)
                {
                    return NotFound();
                }

                var Penalty = (_context.Penalties != null)?_context.Penalties
                                                .Include(b=>b.Borrowing)
                                                .ThenInclude(b=>b.Book)
                                                .Include(b=>b.Borrowing)
                                                .ThenInclude(b=>b.Client)
                                                        .ToList().Find(b=>b.Id == id):null;
                if(Penalty == null){
                    TempData["ErrorMessage"] = "Multa não encontrada";
                    return RedirectToAction("Index");
                }
                return View(Penalty);
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }

        [Authorize]
        public IActionResult Pay(int? id)
        {
            try{
                if(id == null)
                {
                    return NotFound();
                }

                var Penalty = (_context.Penalties != null)?_context.Penalties
                                                .Include(b=>b.Borrowing)
                                                .ThenInclude(b=>b.Book)
                                                .Include(b=>b.Borrowing)
                                                .ThenInclude(b=>b.Client)
                                                        .ToList().Find(b=>b.Id == id):null;
                if(Penalty == null){
                    TempData["ErrorMessage"] = "Multa não encontrada";
                    return RedirectToAction("Index");
                }
                return View(Penalty);
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }
        }

        [HttpPost,ActionName("Pay")]
        [Authorize]
        public IActionResult PayPenalty(int? id)
        {

            try{
                if(id == null)return NotFound();
                var Penalty = _context.Penalties.Include(p => p.Borrowing).ToList().Find(p => p.Id == id);

                if (Penalty == null) return NotFound();
                Penalty.Solved = true;
                _context.Penalties.Update(Penalty);

                    if(Penalty.Borrowing !=null)
                    {
                        var Client = _context.Clients.Find(Penalty.Borrowing.ClientId);
                        if(Client!=null)
                        {
                            Client.Active = true;
                            _context.Clients.Update(Client);
                        }
                    }

                _context.SaveChanges();
                TempData["SuccessMessage"] = "Pagamento Concluido";
                return RedirectToAction("Index");
            }catch(Exception e)
            {
                TempData["ErrorMessage"] = "Ocorreu um problema tente outra vez";
                return RedirectToAction("Index");
            }

        }

         private void setPaginationConfig(int page, double size)
        {
                double pages = _context.Penalties.Count() / size;
                ViewData["total_pages"] = Math.Ceiling(pages);
                Console.WriteLine("TOTAL PAGES = " +ViewData["total_pages"] );
                ViewData["actual_page"] = page;
                ViewData["next_page"] = page + 1;
                ViewData["prev_page"] = page==1?page:page - 1;
        }
    }
}

Views/Borrowing/Create.cshtml
@model Bookstore.Models.Borrowing
@{
    ViewData["Title"] ="Emprestar Livro";
    var Book = ViewData["Book"] as Book;
    var Client = ViewData["Client"] as Client;
}
<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 ">
            Concluir Emprestimo
        </h2>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs">
            
        <form class="form" asp-action="Create" method="post" >
                    <input type="hidden" name="ClientId" id="ClientId" value="@Client.Id">
                    <input type="hidden" name="BookId" id="BookId" value="@Book.Id">
                    <div class="form-row">
                        <div class="form-group col-12 col-md-3 mr-1">
                            <label for="">Livro</label>
                            <input type="text" value="@Book.Title" class="form-control" disabled>
                        </div>
                        
                        <div class="form-group col-12 col-md-3 mr-1">
                            <label for="">Cliente</label>
                            <input type="text" value="@Client.Name" class="form-control" disabled>
                        </div>
                        <div class="form-group col-12 col-md-3 mr-1">
                            <label for="">Valor</label>
                            <input type="text" value="@Book.Value" class="form-control" disabled>
                        </div>
                        <div class="form-group col-12 col-md-2 mr-2">
                            <label for="">Data de Devolução</label>
                            <input type="date" name="ReturnDate" id="ReturnDate" class="form-control" 
                                >
                            <span class="text-danger" asp-validation-for="ReturnDate"></span>
                        </div>
                                
                    </div>
                    <div class=" form-row mt-3">
                        <div class="form-group col-12 col-md-5">
                            <input type="submit" value="Concluir" class="w-50 btn btn-md btn-primary">
                    
                        </div>
                    </div>
                </form>
           

        </div>


    </div>
</main>

Views/Borrowing/Index.cshtml
@model IEnumerable<Bookstore.Models.Borrowing>
@{
    ViewData["Title"] ="Lista de Empréstimos";
    var nextPage = ViewData["next_page"];
    var prevPage = ViewData["prev_page"];
    var actualPage = ViewData["actual_page"];
    var totalPages = int.Parse(ViewData["total_pages"].ToString());
}

<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 ">
            Lista de Empréstimos
        </h2>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs">
            
            <div class="p-2 d-flex justify-content-between align-items">
              <div>
                <a class="btn btn-primary" asp-action="SelectBook">Novo Empréstimo</a>
              </div>
              
            </div>


            <div class="border rounded">
              <table class="table">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Livro</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Data de Empréstimo</th>
                    <th scope="col">Data de Devolução</th>
                    <th scope="col">Estado </th>
                    <th scope="col">Prazo Violado? </th>
                    <th scope="col">Acções</th>
                  </tr>
                </thead>
                <tbody>
                    @if(Model != null){
                  @foreach(var item in Model){
                    
                    <tr style="color: black;">
                        <td>@item.Id</td>
                        <td> @item.Book.Title</td>
                        @* <td> @item.Isbn</td> *@
                        <td> @item.Client.Name</td>
                        <td> @item.RequestDate</td>
                        <td> @item.ReturnDate</td>
                        <td>
                        @if(item.Returned==true)
                        {
                            <span class="text-primary">Devolvido</span>    
                        }else{
                            <span class="text-info">Requisitado</span>
                        }
                        </td>
                        <td>
                        @if(item.PrizeViolated==true)
                        {
                            <span class="text-danger ">Violado</span>    
                        }else if((item.ReturnDate < DateTime.Now) && item.Returned == false){
                            <span class="text-danger ">Violado</span>
                        }
                        else{
                            <span class="text-secondary ">Não</span>
                        }
                        </td>
                        <td class="d-flex">
                            @if(item.Returned != true)
                            {
                                <a  class=" btn  btn-success btn-sm mr-3"
                                asp-action="Show" asp-route-id="@item.Id">
                                    Devolver
                                </a>
                            }else{
                              <a  class=" btn  btn-info btn-sm mr-3"
                                asp-action="Show" asp-route-id="@item.Id">
                                    Detalhes
                                </a>
                            } 
                            @{
                              var modalId = "modal" + item.Id;
                            }
                            <a class=" btn  btn-danger btn-sm mr-3"
                            role="button" data-toggle="modal" 
                                data-target="#@modalId">
                                Eliminar
                            </a>
                            
                        </td>
                    
                        
                    </tr>
                        <!--  MODAL DE DETALHES-->
                    <div class="modal fade" id="@modalId" role="dialog" 
                        tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h3 class="modal-title" id="exampleModalLabel">Remover Empréstimo</h3>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">
                            <div class="">
                                  <h4 class="text-center mb-2">Deseja realmente eliminar este Empréstimo?</h4>
                                  <form asp-action="Delete" method="post">
                                    <input type="hidden" name="id" value="@item.Id">
                                    <div class="d-flex justify-content-center">
                                        <input type="submit" value="Eliminar" class="btn btn-danger mr-3">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                    </div>
                                  </form>
                           </div>
                          </div>
                          
                        </div>
                      </div>
                    </div>
                    <!-- FIM DO MODAL DE DETALHES -->
                    }
                    }else{
                        <tr>
                            <td colspan="3" class="text-center">Sem Resultados</td>
                        </tr>
                    }
                </tbody>
              </table>
            </div>
            <div class="mt-2 p-2 w-full d-flex justify-content-center">
              <div class="">
                     <nav aria-label="Page navigation example">
                        <ul class="pagination">
                          @if((int)prevPage==(int)actualPage)
                          {
                            <li class="page-item disabled"><a class="page-link " asp-action="Index" asp-route-page="@prevPage">Anterior</a></li>
                          }else{
                            <li class="page-item"><a class="page-link  " asp-action="Index" asp-route-page="@prevPage">Anterior</a></li>
                          }
                          @for(int i = 1;i <= totalPages; i++)
                          {
                            @if(actualPage.ToString() == i.ToString())
                            {
                              <li class="page-item bg-primary  text-light active"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li> 
                            }
                            else{
                              <li class="page-item  text-light"><a class="page-link" asp-action="Index" asp-route-page="@i">@i</a></li> 
                            }
                          }
                          @if((int)nextPage>totalPages)
                          {
                            <li class="page-item disabled"><a class="page-link  " asp-action="Index" asp-route-page="@nextPage">Próximo</a></li>
                          }else{
                            <li class="page-item"><a class="page-link  " asp-action="Index" asp-route-page="@nextPage">Próximo</a></li>
                          }
                          
                        </ul>
                      </nav> 
              </div>
            </div>

        </div>


    </div>
</main>

Views/Borrowing/Show.cshtml
@model Bookstore.Models.Borrowing
@{
    ViewData["Title"] ="Emprestimo";
}

<main class="h-full pb-16 overflow-y-auto">
    <div class="container grid px-0 mx-auto">
        <h2 class="my-6 text-2xl font-semibold text-gray-700 ">
            Emprestimo
        </h2>

        <!-- TABELA  -->
        <div class="w-full p-3 overflow-hidden bg-white rounded-lg shadow-xs text-dark">
            
            <div class="border rounded p-2 text-dark">
                
                <div class="row text-dark mb-1">
                    <div class="col-12 col-md-4">
                        <h5>Livro: <span style="font-weight: lighter;"> @Model.Book.Title</span></h5>
                    </div>
                    <div class="col-12 col-md-4">
                        <h5>Cliente: <span style="font-weight: lighter;">@Model.Client.Name</span></h5>
                    </div>
                    <div class="col-12 col-md-4">
                        <h5>Data de Emprestimo: <span style="font-weight: lighter;">@Model.RequestDate</span></h5>
                    </div>
                </div>
                <div class="row text-dark">
                    <div class="col-12 col-md-4">
                        <h5>Data de Devolução: <span style="font-weight: lighter;">@Model.ReturnDate</span></h5>
                    </div>
                    <div class="col-12 col-md-4">
                        <h5>Estado: 
                            @if(Model.Returned == false)
                            {
                                <span class="text-primary" style="font-weight: bolder;">Requisitado</span>
                            }else{
                                <span class="text-success" style="font-weight: bolder;">Devolvido</span>
                            }
                        </h5>
                    </div>
                    <div class="col-12 col-md-4">
                         <h5>Prazo Violado: 
                            @if(Model.PrizeViolated == true)
                            {
                                <span class="text-danger">Violado</span>
                            }else{
                                <span class="text-success" >Não Violado</span>
                            }
                        </h5>
                    </div>
                </div>
                    
                    
                </div>
                    <div class="p-2 mt-1">
                        <form asp-action="Devolver" method="post">
                            <input type="hidden" asp-for="Id">
                            <div class=" form-row mt-3">
                                @if(Model.Returned == false)
                                {
                                <div class="form-group col-12 col-md-2">
                                    <input type="submit" value="Devolver" class=" btn btn-sm btn-primary">
                                </div>
                                }
                                @if((Model.PrizeViolated && Model.Returned == true) && (Model.Penalty==null)){
                                <div class="form-group col-12 col-md-3">
                                    <a asp-controller="Penalty" asp-action="Create" 
                                        asp-route-id="@Model.Id" class="btn btn-sm btn-warning">Aplicar Multa</a>
                                </div>
                                }
                            </div>
                        </form>
                        
                    </div>


                @if(Model.Penalty!=null){
            <div class="border rounded p-2 mt-3">
                <h4 class="mb-2">Multa Aplicada</h4>
                <div class="row">
                    <div class="col-12 col-md-3">
                        <h5 class="fw-bold">Data: <span style="font-weight: lighter;">@Model.Penalty.DateAplied</span></h5>
                    </div>
                    <div class="col-12 col-md-3">
                        <h5 class="fw-bold">Valor da Multa: <span style="font-weight: lighter;">@Model.Penalty.Value</span></h5>
                    </div>
                    <div class="col-12 col-md-3">
                        @if(@Model.Penalty.Solved){
                            <h5 class="fw-bold">Estado: <span class="text-success" style="font-weight: lighter;">Pago</span></h5>
                        }else{
                            <h5 class="fw-bold">Estado: <span class="text-danger fw-bold" >Não Pago</span> 
                                <a  class=" btn  btn-success btn-sm mr-3"
                                asp-controller="Penalty"    asp-action="Pay" asp-route-id="@Model.Penalty.Id">
                                    Pagar
                                </a>
                            </h5>
                        }
                    </div>
                </div>
            </div>
            }
            </div>
            

        </div>


    </div>
</main>